### ISSUE TITLE
Lisence Suggestion: AGPL

### ISSUE THREAD

**Issue by apkallum** [pirate/pennybags#168]
In your decision on which open-source license to assign, I ask you to consider AGPL. 

AGPL is better than GPL given that it [mandates the users who host the application to publish any modifications they make](https://www.aberlawfirm.com/agpl-and-what-every-saas-company-should-know-about-it/), and thus is more appropriate for SaaS projects.

**Comment by apmilen** [comment]
added:

https://github.com/apmilen/homenet/commit/718c914e968bb60e2a7175e39bdc0202f6587de8
