### ISSUE TITLE
sign emails so they don't appear like spam

### ISSUE THREAD

**Issue by apmilen** [pirate/pennybags#196]
I forget what kind of DNS record this needs (DKIM?) but right now our emails have scary looking warnings cause they can't verify its coming from pushforward.nyc

**Comment by pirate** [comment]
we usually send through mailgun, I can set that up with proper SPF+DKIM+DMARC records.

**Comment by pirate** [comment]
@apmilen https://support.google.com/a/answer/174126?hl=en can you generate a DKIM key in your google admin console and send it to me
